#! /usr/bin/env python3
import requests, sys, shutil, tempfile, json, time

app_info = {
    "app_name": "Anonymize data file",
    "language": "PYTHON",
    "params": [
        {
            "name": "mytext",
            "type": "TEXT",
            "label": "",
        },
        {
            "name": "mytextlist",
            "type": "TEXT_LIST",
            "label": "",
        },
        {
            "name": "mynumber",
            "type": "NUMBER",
            "label": "",
        },
        {
            "name": "mynumberlist",
            "type": "NUMBER_LIST",
            "label": "",
        },
        {
            "name": "myboolean",
            "type": "BOOLEAN",
            "label": "",
        },
        {
            "name": "myfile",
            "type": "FILE",
            "label": "",
        }
    ]
}
code_dir = './env'

temp_name = tempfile.mkstemp()[1]
zip_file = shutil.make_archive(temp_name, 'zip', root_dir=code_dir, base_dir='./')

def show(r):
    print(json.dumps(r.json(), indent=4))

# make app
print('Create app')
r = requests.post('http://localhost:5001/app/create', files={
    'app_info': (None, json.dumps(app_info)),
    'code_file': ('code.zip', open(zip_file, 'rb'))
})

app_id = r.json()['app_id']
show(r)
print('-------------------------------------------------------------')

# wait for build
while True:
    r = requests.get('http://localhost:5001/app/{}'.format(app_id))
    t = r.json()
    if t['app_detail']['app_status'] == 'BUILDING':
        time.sleep(0.5)
    else:
        break

# call
print('Call app')
r = requests.post('http://localhost:5001/app/{}/execute'.format(app_id), files={
    'mytext': (None, 'Do anything you like'),
    'mytextlist': (None, '["Van", "Tien", "Cuong"]'),
    'mynumber': (None, '100'),
    'mynumberlist': (None, '[1, 2, 3]'),
    'myboolean': (None, 'true'),
    'myfile': ('file', open('./env/main.py', 'rb'))
})

call_id = r.json()['call_id']
show(r)
print('-------------------------------------------------------------')

# get result
print('Get result')
while True:
    r = requests.get('http://localhost:5001/call/{}'.format(call_id))
    t = r.json()
    if r.ok:
        if t['call_detail']['call_status'] == 'STARTED':
            time.sleep(0.5)
            continue
        else:
            print('----------------')
            output = t['call_detail']['output']
            print(output)
            print('-------------------------------------------------------------')
            break

