#! /usr/bin/env python3
import requests, sys, shutil, tempfile, json

app_info = {
    "app_name": "Anonymize data file",
    "language": "PYTHON",
    "params": [
        {
            "name": "mytext",
            "type": "TEXT",
            "label": "",
        },
        {
            "name": "mytextlist",
            "type": "TEXT_LIST",
            "label": "",
        },
        {
            "name": "mynumber",
            "type": "NUMBER",
            "label": "",
        },
        {
            "name": "mynumberlist",
            "type": "NUMBER_LIST",
            "label": "",
        },
        {
            "name": "myboolean",
            "type": "BOOLEAN",
            "label": "",
        },
        {
            "name": "myfile",
            "type": "FILE",
            "label": "",
        }
    ]
}
"1","[\"1\"]"
code_dir = './env'

temp_name = tempfile.mkstemp()[1]
zip_file = shutil.make_archive(temp_name, 'zip', root_dir=code_dir, base_dir='./')

# make app
r = requests.post('http://localhost:5001/app/create', files={
    'app_info': (None, json.dumps(app_info)),
    'code_file': ('code.zip', open(zip_file, 'rb'))
})

app_id = r.json()['app_id']
print('app_id\t', app_id)


# call
r = requests.post('http://localhost:5001/app/{}/execute'.format(app_id), files={
    'mytext': (None, 'Do anything you like'),
    'mytextlist': (None, '["Van", "Tien", "Cuong"]'),
    'mynumber': (None, '100'),
    'mynumberlist': (None, '[1, 2, 3]'),
    'myboolean': (None, 'true'),
    'myfile': ('file', open('./env/main.py', 'rb'))
})

call_id = r.json()['call_id']
print('call_id\t', call_id)

# get result
while True:
    r = requests.get('http://localhost:5001/call/{}'.format(call_id))
    if r.ok:
        print('call_output')
        output = r.json()['output']
        print(output)
        break

