#! /usr/bin/env python3
import requests, sys, shutil, tempfile, json

app_info = {
    "app_name": "Anonymize data file",
    "language": "PYTHON",
    "params": [
        {
            "name": "algorithm",
            "type": "TEXT",
            "label": "Algorithm",
            "description": "Algorithm to anonymize dataset"
        },
        {
            "name": "keyvalue_field_2",
            "type": "TEXT",
            "label": "Another test field",
        },
        {
            "name": "file_to_anonymize",
            "type": "FILE",
            "label": "File to anonymize",
            "description": "A csv data file"
        }
    ]
}
"1","[\"1\"]"
code_dir = './env'

temp_name = tempfile.mkstemp()[1]
zip_file = shutil.make_archive(temp_name, 'zip', root_dir=code_dir, base_dir='./')

# make app
r = requests.post('http://localhost:5001/app/create', files={
    'app_info': (None, json.dumps(app_info)),
    'code_file': ('code.zip', open(zip_file, 'rb'))
})

app_id = r.json()['app_id']
print('app_id', app_id)


# call
r = requests.post('http://localhost:5001/app/{}/execute'.format(app_id), files={
    'algorithm': (None, 'Do anything you like'),
    'keyvalue_field_2': (None, 'Another key value'),
    'file_to_anonymize': ('file', open('./env/main.py', 'rb'))
})

call_id = r.json()['call_id']
print('call_id', call_id)

# get result
while True:
    r = requests.get('http://localhost:5001/call/{}'.format(call_id))
    if r.ok:
        output = r.json()['output']
        print('call_output:', output)
        break

