#! /usr/bin/env python3
import requests, sys, shutil, tempfile, json, time

app_info = {
    "app_name": "Anonymize data file",
    "language": "PYTHON",
    "params": [
        {
            "name": "algorithm",
            "type": "TEXT",
            "label": "Algorithm",
            "description": "Algorithm to anonymize dataset"
        },
        {
            "name": "file_to_anonymize",
            "type": "FILE",
            "label": "File to anonymize",
            "description": "A csv data file"
        }
    ]
}

code_dir = '../example_apps/python/hello-world'
temp_name = tempfile.mkstemp()[1]
zip_file = shutil.make_archive(temp_name, 'zip', root_dir=code_dir, base_dir='./')

# make app
r = requests.post('http://localhost:5001/app/create', files={
    'app_info': (None, json.dumps(app_info)),
    'code_file': ('code.zip', open(zip_file, 'rb'))
})

print(json.dumps(r.json(), indent=4))
app_id = r.json()['app_id']


# call
r = requests.post('http://localhost:5001/app/{}/execute'.format(app_id), files={
    'algorithm': (None, 'Do anything you like'),
    'file_to_anonymize': ('file', open('../README.md', 'rb'))
})

print(json.dumps(r.json(), indent=4))
call_id = r.json()['call_id']

time.sleep(1)

# get result
r = requests.get('http://localhost:5001/call/{}'.format(call_id))
if r.ok:
    output = r.json()['output']
    print('call_output:', output)
    print(json.dumps(r.json(), indent=4))
else:
    print(json.dumps(r.json(), indent=4))