#! /usr/bin/env python3
import requests, sys, shutil, tempfile, json, pathlib

app_info = {
    "app_name": "Anonymize data file",
    "language": "PYTHON",
    "params": [
        {
            "name": "algorithm",
            "type": "TEXT",
            "label": "Algorithm",
            "description": "Algorithm to anonymize dataset"
        },
        {
            "name": "file",
            "type": "FILE",
            "label": "File to anonymize",
            "description": "A csv data file"
        }
    ]
}


code_dir = pathlib.Path(__file__).parent.absolute() / './app'
avatar_url = 'https://hoanghamobile.com/tin-tuc/wp-content/uploads/2019/11/che-do-toi-tren-zalo-1.jpg'

temp_name = tempfile.mkstemp()[1]
zip_file = shutil.make_archive(temp_name, 'zip', root_dir=str(code_dir), base_dir='./')

r = requests.post('http://localhost:5001/app/create', files={
    'app_info': (None, json.dumps(app_info)),
    'code_file': ('code.zip', open(zip_file, 'rb')),
    'avatar_file': ('avatar', requests.get(avatar_url).content)
})

print('status:', r.status_code)
print(json.dumps(r.json(), indent=4))

error = r.json()['error']
if error != "":
    print()
    print(error)